name: Node.js CI with Docker

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-node-app .

    - name: Run tests inside Docker container
      run: docker run my-node-app

